export const funnyNames = [
    'Bob McMuffin',
    'Chad Thundercock',
    'Sir Loinsteak',
    'Jimmy NoToes',
    'Albie Back',
    'Barb Dwyer',
    'Hugh Jass',
    'Anita Bath',
    'Ben Dover',
    'Sal Monella',
    "Rick O'Shea",
    'Dustin Trousers',
    'Stan Dupp',
    'Pat Myback',
    'Ella Vator',
    'Bill Board',
    'Sue Permann',
    'Otto Correct',
    'Paige Turner',
    'Terry Bull',
];